project:
  type: website
  output-dir: C:\Users\mthoma14.stu\OneDrive\Documents\GitHub\E-Portfolio

website:
  title: "Your E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Publications
      - href: content.qmd
        text: Content & Deliverables
      - href: contact.qmd
        text: Contact info

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

